### PR TITLE
Osgeolive

### PR DESCRIPTION
**Pull request by epifanio**
Renamed GSOC to GSoC-2015 and removed placeholders

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @epifanio 
I will close #3 since this supersedes it

**Comment by epifanio** [comment]
I've reduced the number of notebook, excluing extra grass notebooks, and fixed a path with last 2 commits.

**Comment by epifanio** [comment]
This PR involve the following dependencies:

already installed by other projects:

```
gdal
ossim
grass
numpy
scipy
matplotlib
psycopg
cesium-js
```

Specific to this PR:

```
pyproj
geocoder [+ ratelim]
geographiclib
cesiumwidget [+ czml, pygeoif]
```
- The footprint in mb is 9.4 mb
- The notebooks included in this PR will work with both ipython notebook or jupyter notebook with absolutely no differences.
- The complete list of topics implemented is visible on [nbviewer](http://nbviewer.jupyter.org/github/epifanio/OSGeoLive-Notebooks/blob/osgeolive/GSoC-2015/Introduction.ipynb)
  _note at the above link: not all the hyperlink are working outside the OSgeo-live environment, and the navigation menu' is not rendered in nbviewer_

**Comment by kalxas** [comment]
Thanks @epifanio 
For the record, I am in favor of merging this PR without minimizing the size footprint (as it was small already)
But as stated in my last e-mail, I will leave the decision of merging or not to you and @darkblue-b

**Comment by epifanio** [comment]
I replied to the e-mail list. Thanks for taking care of this.

**Comment by kalxas** [comment]
Merging after a motion passed in the mailing list

**Pull request merged**
