### PR TITLE
SciTools courses; GPL

### PR DESCRIPTION
**Pull request by darkblue-b**
add `SciTools-courses`, which consists of four directories of a single Jupyter Notebook, each.. GPL license included  .. Richard Hattersly says "feel free to crib from these" at his SciPy 2014 lecture

### CODE REVIEW

**Comment by darkblue-b** [comment]
9MB on disk, no large binary data

**Comment by darkblue-b** [comment]
note - this PR makes a single directory at the top level

```
/home/shared/OSGEO/OSGeoLive-Notebooks$ ls
GSoC-2015  index.ipynb                             projects   SciTools-courses
images     introduction-to-jupyter-notebook.ipynb  README.md
```

**Comment by camerons** [comment]
As we are 1 day away from osgeolive 9.5 RC, I don't think new functionality such as this should be included for this release, it should wait till our next release cycle 10.0

**Comment by kalxas** [comment]
+1 to merge after 9.5 release

**Comment by darkblue-b** [comment]
"new functionality" ??  this is a directory with four files .. fail

**Pull request merged**
