### PR TITLE
Meging work done during Gsoc2015

### PR DESCRIPTION
**Pull request by epifanio**
this PR  add the notebooks developed during GSOC2015

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @epifanio I will make a nightly build with this branch to test

**Comment by kalxas** [comment]
http://aiolos.survey.ntua.gr/gisvm/dev/osgeo-live-nightly-gsoc-amd64-a0263a5.iso

**Comment by epifanio** [comment]
Kalxas, there is a missed deb for a python library i'm using in a couplt of notebooks:  [geocoder](https://pypi.python.org/pypi/geocoder) it should not introduce any additional dependency. I'm testing the iso right now.

**Comment by kalxas** [comment]
@epifanio the deb packages for geocoder and ratelim are in our ppa

**Comment by epifanio** [comment]
Cool, I added `geocoder` in the jupyter installer, does it install directly `ratelim` , right?

**Comment by kalxas** [comment]
Yes it does

**Comment by kalxas** [comment]
I am in the process of running all notebooks on the latest iso.
@epifanio any reason why projects/rasterio was deleted?
I also see that projects/GRASS is missing, has this been merged with the GSoC folder?

**Comment by epifanio** [comment]
I didn't remove the rasterio directory, perhaps it was not there when I started this pr.

**Comment by kalxas** [comment]
@epifanio correct it was not removed.

**Comment by kalxas** [comment]
Superseded by #5

**Pull request closed without merging**
